### ISSUE TITLE
Would this allow D3D11 -> Vulkan via DXVK on Windows?

### ISSUE THREAD

**Issue by Espionage724** [fholger/vrperfkit#1]
Saw a few commits like https://github.com/fholger/vrperfkit/commit/d7ade8d87159ed07b18ddfc95536204021583bb8 and I was wondering if DXVK could be used on Windows, or in other words allow D3D11 VR games like Blade & Sorcery to run with Vulkan?

I've heard that DXVK couldn't be used on Windows for VR due to dxgi or something like that.

**Comment by Espionage724** [comment]
Is there anything special that needs to be done to use DXVK with this? I tried dropping DXVK's `d3d11.dll` in the same folder as vrperfkit's `dxgi.dll` and `vrperfkit.yml`, but both Blade & Sorcery and Beat Saber crash with an error about not being able to change the resolution.

- [Screenshot of error](https://i.imgur.com/1o0afrx.png)
- [vrperfkit.log](https://pastebin.com/bn4s7Ku5)
- [BladeAndSorcery_d3d11.log](https://pastebin.com/p6bdDB5U)

**Comment by fholger** [comment]
You need to have vrperfkit as dxgi.dll, then put dxvk's d3d11.dll and dxgi.dll into a subfolder called dxvk. Then you need to add a new section to the config file:
```
dxvk:
    enabled: true
```

But I was being serious. This has absolutely zero benefits and a couple of disadvantages. There's a reason I'm not promoting this feature :)

**Comment by fholger** [comment]
Going to close this, as I don't currently have any plans to invest more time into this.

**Comment by CaiMiao** [comment]
just coming here to say thank you for implementing this.

> But I was being serious. This has absolutely zero benefits and a couple of disadvantages. There's a reason I'm not promoting this feature :)

well i'm trying to opt-in DXVK for Honey Select 2, which is horribly optimized.
DXVK is a huge free performance boost the game from around 70f or 90f in title screen on my device, along with a common mod setup.
there is still some reason why ppl wants DXVK...

**Comment by CaiMiao** [comment]
just coming here to say thank you for implementing this.

> But I was being serious. This has absolutely zero benefits and a couple of disadvantages. There's a reason I'm not promoting this feature :)

well i'm trying to opt-in DXVK for Honey Select 2, which is horribly optimized.
DXVK is a huge free performance boost for the game from ~50f  to ~70f or ~90f in title screen on my device, along with a common mod setup (after disabling major fps killer plugin like *FK and IK*).
there is still some reason why ppl wants DXVK...

**Comment by CODPHISH** [comment]
> just coming here to say thank you for implementing this.
> 
> > But I was being serious. This has absolutely zero benefits and a couple of disadvantages. There's a reason I'm not promoting this feature :)
> 
> well i'm trying to opt-in DXVK for Honey Select 2, which is horribly optimized. DXVK is a huge free performance boost for the game from ~50f to ~70f or ~90f in title screen on my device, along with a common mod setup (after disabling major fps killer plugin like _FK and IK_). there is still some reason why ppl wants DXVK...

can you please tell me how to optimize hs2 vr，i use the BR R11 verison，the fps slutter all the time，but cpu and mem only use 10%~20%，GPU 100% load（RTX3060）

**Comment by CaiMiao** [comment]
> can you please tell me how to optimize hs2 vr，i use the BR R11 verison，the fps slutter all the time，but cpu and mem only use 10%~20%，GPU 100% load（RTX3060）

DXVK does not allow utilizing VR on windows environment (at least at the moment)
