### ISSUE TITLE
FFR in VR Performance Toolkit v0.2

### ISSUE THREAD

**Issue by huliqan** [fholger/vrperfkit#10]
FFR on my GTX1080ti no works???

**Comment by fholger** [comment]
Like the readme says, only VRS is implemented right now, and that requires an RTX or GTX 16xx card. So no, it is not available on a GTX 1080.

**Comment by Houndmux** [comment]
I tried it in IL2 and Elite Dangerous. The upscaling options work, but toggling FFR does not show a visible difference in any of the games, even if I enter low values for the FFR radii. RTX 2080 TI. Is it to be expected that FFR does not always work?
I suggest you include in the readme that people reset their opanvr_api.dll to the original file and verify the integrity of their game files first, just to be sure.

**Comment by mattlant** [comment]
> I tried it in IL2 and Elite Dangerous. The upscaling options work, but toggling FFR does not show a visible difference in any of the games, even if I enter low values for the FFR radii. RTX 2080 TI. Is it to be expected that FFR does not always work?
> 
> I would also suggest you include in the readme that people reset their opanvr_api.dll to the original file and verify the integrity of their game files first, just to be sure.
> 
> edit: the lofgile says: (DEBUG) VRS: Single eye target, don't know which eye

Same here when toggling FFR on.

**Comment by fholger** [comment]
Yeah, then those games do not currently work with FFR.

**Comment by Zorinco96** [comment]
For DCS World I also get the same DEBUG error of VRS: Single eye target, don't know which eye. Is there some sort of a workaround to enable it or anything that needs to be tweaked in the Nvidia Control Pannel?

**Comment by fholger** [comment]
No, it simply means that the games are not currently supported by VRPerfKit. There's nothing you can do about it until I figure out a way to detect or guess when the game is rendering the left or right eye.

**Comment by Zorinco96** [comment]
With DCS World, I know you can choose whether or not the 2D mirror uses either the left eye or the right eye as the source (default left eye). I assume that's not what'll be needed though?

**Comment by fholger** [comment]
No, that's irrelevant. When a game renders a frame, it needs to render both the left and the right eye views. Some games, like DCS, render the eyes into separate textures. Unfortunately, it isn't trivial to decide when it is rendering which eye, as there can be multiple render targets involved, and the game might also be switching between them arbitrarily. And if I don't know which eye is currently rendering, I cannot apply the correct fixed foveated rendering pattern for that eye.

There is an assumption that can be made that games typically render the left eye first and then the right eye. But even with that assumption, it might involve multiple render steps per eye, and if I don't know how many belong to one eye, I might apply the wrong pattern.

**Comment by BrziJoe** [comment]
Fholger, that what you described above is probbably what happens to IL-2. The right eye is properly rendered, and in left eye screen there are FFR for right and rigt eye together.

I would like to donate one part of IL-2 to you, if that can help. Or do you think we need support from developer?
What do you say?

**Comment by fholger** [comment]
I'm sorry, I do not currently accept donations in any form. Donations create a form of obligation that I'm not willing to take on :) I will try to make as many games compatible as I can, but with fixed foveated it just will never work with all games, and it will only have a beneficial effect in a few of those games.

**Comment by BrziJoe** [comment]
I totaly understand you, even if I do not expect any kind of obligation in return. I will ask developers to play a little with your tool, maybe they can figure it. At end, it is in their best interest to have foveated working in IL-2.

**Comment by drowhunter** [comment]
I wonder if theres a way  to start tracking a list of known working games, or the reverse.

**Comment by DJSlane** [comment]
I've yet to find a working VRS or FFR game.

**Comment by fholger** [comment]
Most Unity and Unreal games should work, although whether or not it actually improves performance I can't say. That's very game-dependent. Also working are Skyrim, Stormland, Lone Echo 1, Asgard's Wrath. Again, I haven't actually measured the performance gain (if any), but VRS itself is active in those games.

**Comment by DJSlane** [comment]
https://github.com/cedriclmenard/vrperfkit has a solution for DCS. I couldn't get it to work for canted displays, and it loses the ability to use hotkeys for all the FSR/CAS/NIS functions, but clearly works for DCS (non Pimax)!

**Comment by DJSlane** [comment]
Also wonder if it works for the other listed games, IL-2 and Elite Dangerous?

**Comment by redcloud111** [comment]
BrziJoe, if you hear anything about FFR working in IL2, can you make a post on the forums? I am using vrperfkit and just realized after an hour of testing that FFR will not work in Il2. I'll periodically check back here, but I read the Il2 forum daily. Thanks to fholger and everyone for all their hard work with this great tool.

**Comment by BrziJoe** [comment]
Of course I will post everywhere :).
I contacted IL-2 developer 2 times by now, but didn´t get any answer.  I do not know if they do not have will for it (not likely), or is that currently just too big bite for them and their schedule (most likely).
I explained about importance of foveated rendering in IL-2, and that game can not work with eye tracking (active foeated) if it´s not able to do fixed foveated.
I wish we have it working already.

There is another problem here; vrperfkit can not be used in IL-2 multiplayer (it is recognized by game as "mod"), just openvr_fsr and _foveated. I hope we will not need to choose between FSR upscaling and foveated, as we need booth.

**Comment by redcloud111** [comment]
Ah, I didn't realize that about multiplayer and vrperfkit. I will remove the files. Glad to know before tomorrow, when I plan to team up!

My guess is IL2 development team has too much on their plate already. No worries!

**Comment by huliqan** [comment]
FSR from this mode works fine in IL-2GB and in IL-2BoB!

**Comment by fholger** [comment]
vrperfkit v0.3 has experimental support for fixed foveated rendering in games which render the eyes separately. I have no idea if it'll work with DCS or other titles, but it did work for at least one title I tested with. In the worst case, the order of the eyes can be overwritten in the config, so if vrperfkit's guesses are not correct and you have the patience for it, you might figure out the correct order for each game and put that in the config file.

Closing this in favor of #19

**Comment by DJSlane** [comment]
Thank you! I will do just that and report any successes!

**Comment by DJSlane** [comment]
What game was it that you got it working for and which sequence?

________________________________

**Comment by RavenSystem** [comment]
For Il-2 and other games: https://forum.il2sturmovik.com/topic/86271-mod-new-vr-performance-toolkit-rsf/
