### ISSUE TITLE
EAC whitelist

### ISSUE THREAD

**Issue by ni1chigo2115** [fholger/vrperfkit#105]
Speaking of which, is it possible to register on the white list to the EAC?
It is clearly recognized what we need to do and it seems to me that we need to have it whitelisted because the current situation is not very stable in terms of performance.

**Comment by marty1885** [comment]
Second this.

If EAC whitelist requires a code signing key, or even EV code signing key. I'll be more than happy to pay (I know how expensivea EV key is). VR Perf Kit is too important for me to loose in VRChat and their current debacle.

**Comment by fholger** [comment]
I have no clue how to get something on the EAC whitelist. The EAC website contains no information on that; I'm not even sure if I'd have to contact EAC or the specific game developers. Honestly, I don't really have the time nor the willingness to look into this. If this is important to you, you will have to drive this on your own.

**Comment by nReus** [comment]
I believe that with EAC, whatever goes on the whitelist of files for a game is at the mercy of the developer of said game. Simply put, each game has its own set of "trusted" files laid out by its developer. That makes adding vrperfkit to the whitelist impossible unless the developer willingly adds it.

This whole situation is quite a bummer really. The FFR settings in this are literally my saving grace allowing me to remotely achieve playable framerates.

**Comment by ragesaq** [comment]
> 

If you sign your dll with a code signing cert that is publicly trustable EAC should pick it up. Would like to use this in Ghosts of Tabor for FFR

**Comment by marty1885** [comment]
@ragesaq It does not work. I tried signing vrperfkit with my EV code signing cert (the highest level you can get). EAC rejected it.

**Comment by ragesaq** [comment]
Ah, I wonder if different games have it tuned differently, getting the code signed has solved it for certain games for me. Do you mind sharing your code signed dll? I can try it out and maybe find some that do and do not work.

**Comment by marty1885** [comment]
Sorry, I cannot. I do not _own_ the certificate. I just have access to it and allowed to use it for experiments (and actual signing with that cert).
