### ISSUE TITLE
not working with no man sky vr

### ISSUE THREAD

**Issue by qe58hmr** [fholger/vrperfkit#106]
i pulled the 2 files in no man sky its really sharp but its lag unplayable im on quest 2 wire capled my pc 3080 and amd 5900x cpu

**Comment by jacklul** [comment]
No Man's Sky is not using OpenVR anymore - this mod can't work with it

**Comment by krazysh01** [comment]
> No Man's Sky is not using OpenVR anymore - this mod can't work with it

This is incorrect, it still only uses OpenVR (the only alternative would be OpenXR and none of the OpenXR files are present in the game)

**Comment by krazysh01** [comment]
However, No Mans Sky does not use DirectX it used to use OpenGL and then switched over to Vulkan, so it's still incompatible with VRPerfkit, only the old OpenFSR mod works with it (which is unnecessary because the game supports FSR and DLSS in VR)

**Comment by fholger** [comment]
Both openvr_fsr and vrperfkit only support DX11. If the game isn't using that, then it isn't compatible with either.

**Comment by qe58hmr** [comment]
thanks for the replay guys
