### ISSUE TITLE
Not hooking to No Mans Sky

### ISSUE THREAD

**Issue by stirfriedmilk** [fholger/vrperfkit#108]
Log wont generate unless I run the actual exe file inside the folder. But the issue is the game opens in desktop vr theater mode.

**Comment by krazysh01** [comment]
No Mans Sky does not use DirectX11 so is not compatible with VR Perfkit

**Comment by stirfriedmilk** [comment]
Thank you, I didn't know this required dx11 in order for vr perfkit to actually work. It's a shame the game doesn't use DX11. This game would probably be playable in VR with this 😢
