### ISSUE TITLE
Unity game rendering upside down in HMD

### ISSUE THREAD

**Issue by srpattison** [fholger/vrperfkit#11]
Testing this mod with A Township Tale through SteamVR, currently running in Unity 2018 at the moment I believe.

When running the game with this mod the HMD renders the entire world upside down, yet the screen mirror on the monitor is right side up.  HMD is a Steam Index.

Is it possible the devs are using an outdated SDK version that's somehow conflicting with this?

Also the Launcher for this game allows users to choose between SteamVR and Oculus runtimes - SteamVR generally performs better and that's what I'm using. Have not tried running the Oculus runtime, but I can do so if that helps.

**Comment by AydenBurgers** [comment]
Was just about to post this, I was running boneworks on my Rift S with the mod put in and the view was upside down in game

**Comment by fholger** [comment]
Should be fixed with v0.2.2.
