### ISSUE TITLE
Half life Alex. 

### ISSUE THREAD

**Issue by Joshiloveyou** [fholger/vrperfkit#116]
I got the mod to work but the middle circle becomes blocky when moving. 
I'm not sure what eles to do to fix it, any help would be appreciated

**Comment by Crimson-foxGITHUB** [comment]
Add +vr_fidelity_level 3 to your launch options. This will disable dynamic resolution and set it to 100% of the base render resolution for your HMD.

**Comment by Joshiloveyou** [comment]
Thanks, I'll try this later. 1 am here

**Comment by Joshiloveyou** [comment]
> Add +vr_fidelity_level 3 to your launch options. This will disable dynamic resolution and set it to 100% of the base render resolution for your HMD.

Get. Sorry for the late response, that fixed the problem. Thanks for the the help
