### ISSUE TITLE
Trying to use with Neos but it isn't loading

### ISSUE THREAD

**Issue by SnowedInOwl** [fholger/vrperfkit#125]
I keep Getting this error

> 12:42:57 [17792] (!) ERROR: Failed to create graphics resources: Failed creating output swapchain:  (-7000)
12:42:57 [17792] (!) ERROR: Could not initialize graphics resources; game may be using an unsupported graphics API

What can i do to fix it?

**Comment by Crimson-foxGITHUB** [comment]
Are you on an AMD graphics card? If yes, disable FFR.

**Comment by SnowedInOwl** [comment]
I'm not

**Comment by d0x360** [comment]
** Deleted for being completely wrong **

**Comment by SnowedInOwl** [comment]
hmmm

**Comment by d0x360** [comment]
My answer wasnt right.  I was thinking of an HMD called the Neo not the game or virtual social media called Neos.

**Comment by SnowedInOwl** [comment]
well i think i got it to work

**Comment by SmokingAces207** [comment]
Please tell me how you got it to work, I see this error a lot. I think it's partly working, but not the foveating rendering maybe.

**Comment by d0x360** [comment]
What are your driver CP settings?

**Comment by SmokingAces207** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/19428187/195652033-89045f26-8399-4eef-b603-b1f5317bd5f3.png">

![image](https://user-images.githubusercontent.com/19428187/195652107-0efe9749-74bb-475a-8649-c7d18a315234.png)

Is this what you mean? Anything look off to you?

**Comment by SmokingAces207** [comment]
Appreciate your reply too :)

**Comment by d0x360** [comment]
Turn vr variable rate shading off.  Having it set to adaptive could be the
issue.

**Comment by SmokingAces207** [comment]
Will give this a go, thank you! That might make sense, the two are similar features.

**Comment by SmokingAces207** [comment]
Nah that didn't work unfortunately... It's really odd. I am pretty sure FFR is the issue. Although if I turn off all features, I still get that error. But if I only have FSR on, I definitely impacts the image (While throwing that error). However FFR has no affect what so ever, regardless :(

**Comment by SmokingAces207** [comment]
I got a 3060TI so it should support it, on the latest GPU drivers.

**Comment by d0x360** [comment]
The VRS function built into nVidia drivers never really worked properly
AFAIK.  They didn't when I got the 3080ti FTW3 Ultra about 6ish months
after it's launch.

**Comment by SmokingAces207** [comment]
Even did a full uninstall of all GPU drivers on my system and reinstalled again. No joy, I guess no FFR for me. Hope there's a new version that fixes it!

**Comment by SmokingAces207** [comment]
Thanks for your help
