### ISSUE TITLE
Oculus attempt with Pimax?

### ISSUE THREAD

**Issue by DJSlane** [fholger/vrperfkit#14]
I tried the PerfKit with the only two games I own that use Oculus runtime, Lone Echo 1 and 2, but it doesn't seem to work (at least the hotkeys don't). I'm still learning about github and have very basic programming skills. Looking at the build I didn't see how it ties in exactly to the Oculus runtime.

**Comment by fholger** [comment]
Lone Echo 2 uses D3D12, which is not currently supported. Lone Echo 1, however, works fine for me, including hotkeys. Please post your vrperfkit.log file.

**Comment by DJSlane** [comment]
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7895496/vrperfkit.log)

**Comment by fholger** [comment]
Hm, it's loading, but it is not detecting any of the VR APIs. Are you using Virtual Desktop, per chance? If so, can you try a Link variant? It might be that VD with Oculus games just doesn't work.

**Comment by DJSlane** [comment]
No, as I thought about it more , do you think it is because I use Pimax, such that it doesn't hook properly?  Also I tried manually setting the runtime is use to Oculus runtime instead of SteamVR runtime and still no benefit.

**Comment by fholger** [comment]
Yes, that's probably it. Whatever PiTool is doing to get Oculus games running is apparently not compatible.

**Comment by fholger** [comment]
Most likely PiTool is intercepting the loading of the Oculus client DLL and replacing it with their own version. If you can run the game with `debugMode: true` in the config file and post the log, there is a chance I can see what the Pimax replacement is called. If I know that, I might just be able to inject that DLL instead and make it work.

**Comment by DJSlane** [comment]
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7905581/vrperfkit.log)

It just doesn't reveal itself to me. I'm sure it uses OVR server and oculus runttime - if it's not running Pimax comes up and asks to start it.. It also fails to use FPSVR which would indicate use of steamVR, nor does it seem to use Revive. So it's normal to me in terms of Oculus operation, but I have nothing to compare it to as Pimax has always prided themselves on running Oculus "natively"

**Comment by fholger** [comment]
Ah, damn, I removed the relevant log lines because they ended up being a bit too "spammy" even for debug mode. Could you try to rerun this with an older build, e.g. 0.2 or even 0.1? Still with debugMode enabled, it should spew out a pretty large list of DLLs getting loaded in the process.

**Comment by DJSlane** [comment]
no problem

________________________________

**Comment by DJSlane** [comment]
Here's Asgard's Wrath, which I just purchased along with 0.1 PerfKit
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7905715/vrperfkit.log)

**Comment by fholger** [comment]
Hm, still no LoadLibrary lines. Maybe it's only the 0.2 release that had them? I'm not sure right now. You'll notice them when they are there.

**Comment by DJSlane** [comment]
OK here's 0.2 with the lone echo 1
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7905739/vrperfkit.log)

**Comment by DJSlane** [comment]
and .12 with lone echo 1
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7905758/vrperfkit.log)

**Comment by fholger** [comment]
Ok, sorry, apparently those debug outputs never made it into a build. I'll have to provide you with a custom build later today.

**Comment by DJSlane** [comment]
no problem will look for it.

**Comment by fholger** [comment]
Try this build with debugMode on, please:
[dxgi.zip](https://github.com/fholger/vrperfkit/files/7912268/dxgi.zip)

**Comment by DJSlane** [comment]
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7912284/vrperfkit.log)
here ya go

**Comment by fholger** [comment]
Thanks. I'm having to guess here since I can't test it myself, but try this build and see if it does anything:
[dxgi.zip](https://github.com/fholger/vrperfkit/files/7912342/dxgi.zip)

**Comment by DJSlane** [comment]
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7912381/vrperfkit.log)
fails, but perhaps this gives insight

**Comment by fholger** [comment]
How exactly does it fail? Both logs show that it now hooks successfully and creates the necessary upscaling resources, but then it appears to shut down in part. If the game crashes, I'm afraid that's going to be next to impossible for me to debug without access to Pimax hardware.

**Comment by DJSlane** [comment]
Let me try with asgards wrath. Funny that the debug "bugsplat" doesn't even fire.

**Comment by DJSlane** [comment]
For Asgard's Wrath:
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7912479/vrperfkit.log)
this one does start the game, but doesn't show the debug circle, respond to hotkeys etc.

**Comment by fholger** [comment]
Ok, yeah, I'm afraid this isn't going to work. Pimax apparently loads multiple versions of its Oculus replacement DLLs, and while with Asgard's Wrath the mod is correctly hooking the latest version, the functions in there are never called. So it's probably using one of the older versions. I can't make this work properly without actually debugging it myself, which is impossible without Pimax. So unfortunately, this is a no fix for me, sorry.

**Comment by DJSlane** [comment]
No problem. I appreciate the effort and enjoyed the dive! I will contact Pimax. They love to incorporate various features across their software and add it to their launcher. I'll let them consider it.
