### ISSUE TITLE
dxgi.dll or dxgi.dll in x86 folder?

### ISSUE THREAD

**Issue by 0bsidianFox** [fholger/vrperfkit#149]
I want to play payday 2 vr which is win32 which is x86 so should I use the dxgi.dll file found with the rest of the stuff or the one found in the x86 folder? Or should I use the FSR mod?
I am using the quest 2 as my headset.

![image](https://user-images.githubusercontent.com/72424605/209452559-9c7b2c92-aedb-47a5-ad25-606702e3e36f.png)
![image](https://user-images.githubusercontent.com/72424605/209452563-fb249732-db49-49eb-a0c5-9603d09140f5.png)
![image](https://user-images.githubusercontent.com/72424605/209452564-ab692300-b3d9-45ef-9b9a-27bdc9de4a88.png)

**Comment by anivd84** [comment]
for x86 games, you need to use the x86 version dxgi.dll from the x86 folder + file vrperfkit.yml

**Comment by 0bsidianFox** [comment]
TY
