### ISSUE TITLE
Elite Dangerous: log File is written, but no effect

### ISSUE THREAD

**Issue by theBuga** [fholger/vrperfkit#153]
Hi,
I tried to use this tool with Elite Dangerous on Steam together with an Oculus 2.
The DLL is somehow invoked: there is the log file being written. But beside that no effect: no change of behaviour when editing the config file. Nothing to be seen if debug is turned on.
Any ideas what I am doing wrong?
Many thanks,
Buga

**Comment by anivd84** [comment]
![2023-03-06_093743](https://user-images.githubusercontent.com/94529028/223021187-c03f92db-709f-485c-9924-fd3ebed1c7b3.png)
![2023-03-06_093956](https://user-images.githubusercontent.com/94529028/223021201-0cbff99b-aa68-4371-a570-f6d04084a87e.png)
![2023-03-06_094954](https://user-images.githubusercontent.com/94529028/223021972-8184b3f5-eb94-4a13-acc6-e22edb83d03c.png)
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/10894413/vrperfkit.log)

I've checked it now and everything seems to be working well. The debugging circle is visible in the screenshot, the effect is also visible, the logs are attached for comparison.
You would like to provide more information, a screenshot, logs, what settings....

> 

> The DLL is somehow invoked: there is the log file being written. But beside that no effect: no change of behaviour when editing the config file. Nothing to be seen if debug is turned on.

Are you editing a config file while playing? Did I understand you correctly? if so, it doesn't work that way

P.S. and so in general, not a very good result is obtained with this game. it's not worth it.

**Comment by theBuga** [comment]
Many thanks for the quick reply. I will provide additional information as soon as I am back at my Computer, tomorrow evening the latest.

`Are you editing a config file while playing? Did I understand you correctly? if so, it doesn't work that way
`
No, I re-started after re-configuration.

Thanks,
Buga

**Comment by theBuga** [comment]
Hi again,
some additioinal info:

Oculus-App-Version 49.0.0.170.358 (49.0.0.170.358)
![image](https://user-images.githubusercontent.com/24698466/223525271-aeeb8c88-75cb-4d23-893e-106871ac3350.png)
![image](https://user-images.githubusercontent.com/24698466/223525373-8071cba5-55e5-4ad7-a0d7-2c8c980a641e.png)
![image](https://user-images.githubusercontent.com/24698466/223527398-bdde7c12-d436-4c59-9c74-6681a90a656a.png)
![image](https://user-images.githubusercontent.com/24698466/223527453-0fdd8b56-b964-40fe-8d92-baf2d65eeadf.png)
![image](https://user-images.githubusercontent.com/24698466/223527604-ff05a45b-03eb-4588-a44c-1732037526df.png)

I tried different configs, e.g.: (I renamed it to .txt in order to be able to drop it here)
[vrperfkit.txt](https://github.com/fholger/vrperfkit/files/10913179/vrperfkit.txt)

There was no effect, but the dll was somehow invoked without doing much logging:
[vrperfkit.log](https://github.com/fholger/vrperfkit/files/10913201/vrperfkit.log)

Although debug mode was enabled ther is no debugging circle visible:
![Bhotepa (20230307-185835)](https://user-images.githubusercontent.com/24698466/223529726-d4d36342-a51a-483b-9b26-27c3a6e40ae1.jpg)

Maybe you can give me hints what I am doing wrong or what I could try?

Many thanks,
Buga

**Comment by anivd84** [comment]
I understood correctly from your screenshot that you put the files in :
"**C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous**" ?
if this is the case, then you did the wrong thing.
For "Odyssey" you need to put them in :
"**C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-odyssey-64**"
For "Horizons" you need to put them in :
"**C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-64**"

for example, I have them located here in this path, in the folder where the executable file is located "EliteDangerous64.exe"
![2023-03-08_013724](https://user-images.githubusercontent.com/94529028/223546958-5f7819be-02b9-4041-865f-1778b6c00762.png)

**Comment by theBuga** [comment]
Many thanks! That was exactly the problem. In my folder is just the launcher. Now everything works.
