### ISSUE TITLE
Are planned mods still in development?

### ISSUE THREAD

**Issue by RavenSystem** [fholger/vrperfkit#163]
Hi @fholger , I only want to ask about announced planned mods (RDM) Radial Density Masking and Force hidden area mask are or will be developed in the future.

Many thanks.

**Comment by RavenSystem** [comment]
@fholger Please, I want to know if force hidden area mask will be developed. This could give some more performance on games that render the complete square.

**Comment by fholger** [comment]
No, I have no plans to return to vrperfkit. I am too busy with my various VR ports; if I ever do find the time and motivation to continue this work, it would most likely be in the form of a rewrite as a Reshade addon. Continuing the current code base doesn't really make sense to me.

**Comment by RavenSystem** [comment]
@fholger Many thanks for your reply! And congratulations for Half-Life 2 VR Mod and next episodes. I am currently playing at Nova Prospekt, and experience is similar to Alyx, even better in some cases. About VR PerfKit, I will add hidden area mask based on your openvr_foverated mod using parts of radial density mask code, without reconstruction post-process.

For curiosity, is it possible to control input and output resolutions with Reshade? I know that it has a lot of hooks and injectors, but I never tried to figure it.

**Comment by fholger** [comment]
No, but it doesn't matter - from my testing, the only portion of the upscaling that's actually useful in VR is the sharpening. And that's easily done with Reshade at a far lower overall cost. I have been recommending for a while to use CAS sharpening instead of FSR or NIS upscaling.

**Comment by RavenSystem** [comment]
Then, using CAS under Reshade with a lower resolution at SteamVR (Valve Index user here). I must try it. Many thanks!

**Comment by ThickCloud** [comment]
Totally agree re CAS. I am also an index user

**Comment by RavenSystem** [comment]
Many thanks! I close it since it is not a real issue.

**Comment by RavenSystem** [comment]
FYI: I added Radial Density Masking and Force hidden area mask to my fork, and other compatibility options and improvements, like dynamic mode to change radius based on frametime. I will keep developing it adding more improvements. Thanks!

https://github.com/RavenSystem/VRPerfKit_RSF
