### ISSUE TITLE
Is there compatibility with The Forest?

### ISSUE THREAD

**Issue by TinyDerp** [fholger/vrperfkit#167]
I was wondering if there was any way to get it running with [The Forest](https://store.steampowered.com/app/242760/The_Forest/), because I'm having awful peformance and I'm searching for anyway to fix that.
Would appreciate any help that I can get to get it working.

**Comment by Zod1234** [comment]
It didn't work with the forest for me, but his other mod https://github.com/fholger/openvr_foveated did.
