### ISSUE TITLE
Can we have DLSS?

### ISSUE THREAD

**Issue by Niter88** [fholger/vrperfkit#170]
I'd love to have support to DLSS on this, it runs a lot faster for RTX cards. The performance boost on VR would be insane.
If any of you have a fork with DLSS support, please, tell me. I would even help it with code and tests if you want to.

Here's some example:
For SkyrimVR: https://www.nexusmods.com/skyrimspecialedition/mods/82179
the base plugin: https://www.nexusmods.com/skyrimspecialedition/mods/80343

This is just an example, but PureDark did a poor job so I avoid this plugin. Also if we have it here, it'll work in any game.

Only thing is, you can't distribute the download for DLSS, so the user would have to download it and drop it in the folder.

(Just leaving noted here that I also opened a ticket on the older project similar to this (by mistake))

**Comment by fholger** [comment]
Not possible. DLSS, FSR 2+ and XeSS all need deep engine integration and cannot be added in a generic way. So these integrations, if they are at all possible, have to be made specifically for a specific game or engine. That's not what this tool does or even can do.
