### ISSUE TITLE
Pavlov crashing

### ISSUE THREAD

**Issue by ryukra** [fholger/vrperfkit#18]
Is it because EAC is blocking the dll?

**Comment by fholger** [comment]
Hard to say, but EAC is definitely a problem. It wouldn't be doing its job if it allowed altered dxgi.dlls to be loaded :)

**Comment by krillme** [comment]
Contractors VR crashes as well when loading dxgi.dll. Both games use UE4, so both probably use Easy Anti Cheat. You can still use the openvr_api.dll mods with these games, however you'll have to choose between upscaling or foveated rendering.

I've compiled a short compatibility list of some games I currently have installed.

PAYDAY 2 - Doesn't accept dxgi or openvr_api (crashes on startup, multiplayer, proprietary "Diesel" engine)
Pavlov VR - openvr_api only (crashes on startup, multiplayer, UE4)
Contractors VR - openvr_api only (crashes on startup, multiplayer, UE4)
BONEWORKS - Accepts both dxgi and openvr_api (singleplayer, unity)
STRIDE - Accepts both dxgi and openvr_api (singleplayer with leaderboards, UE4)
Into The Radius VR - openvr_api only (crashes on startup, singleplayer, UE4)
Blade & Sorcery - Accepts both dxgi and openvr_api (singleplayer, unity)
Hot Dogs, Horseshoes and Hand Grenades - openvr_api only (controllers don't work with dxgi? singleplayer, unity)

I have a ton of VR games so perhaps I could lend a bit of my time to testing certain games to help figure out what the common thread is between them. I would be quick to assume it's EAC crashing the game, but then why does Into The Radius VR crash the exact same way? Certainly a singleplayer game wouldn't have EAC?

**Comment by Crimson-foxGITHUB** [comment]
Pavlov VR tends to crash on startup in general if you look at it wrong.

**Comment by fholger** [comment]
v0.3 works for me in Contractors VR. Don't know about the other games, but there is a decent chance that it was a similar issue and might be fixed with 0.3.

**Comment by krillme** [comment]
Contractors VR will launch now but there seems to be no effect. Log reports FSR and VRS are disabled despite the config file having both enabled. Here is the log file.

[vrperfkit.log](https://github.com/fholger/vrperfkit/files/8307970/vrperfkit.log)

**Comment by fholger** [comment]
It's working fine for me. Your config is defective; see the beginning of the log. It clearly states that it could not read the configuration file, and as a consequence both upscaling and FFR are disabled.

**Comment by krillme** [comment]
Yup, you were right, I accidentally removed a quotation mark somewhere. My bad.

Contractors VR seems to work perfectly now, even the issue with some graphics flickering black or scopes being low resolution when FFR was enabled are gone now. Edit: Nevermind, seems to be an intermittent issue now... maybe it's related to the render order

**Comment by fholger** [comment]
I believe the crash should be fixed, so I'm closing this issue. If there are remaining issues, please open new tickets for them.
