### ISSUE TITLE
IL-2 Sturmovik Great Battles

### ISSUE THREAD

**Issue by huliqan** [fholger/vrperfkit#2]
gamma is very high and all picture is whitish in HMD Oculus Quest2

**Comment by fholger** [comment]
Please try the latest build, I fixed a potential issue with gamma.

**Comment by huliqan** [comment]
ok.thanks!!!

**Comment by huliqan** [comment]
Perfect!  Much better now! Very Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!
but...I can't change gamma (brightness) in game with this mode
