### ISSUE TITLE
Will RDNA2 GPUs support VRS? 

### ISSUE THREAD

**Issue by Loganbogan9** [fholger/vrperfkit#21]
The cards have the hardware capability for it, but is there another issue?

**Comment by fholger** [comment]
Yes - vrperfkit only supports DX11 games, and VRS is not available in DX11. NVIDIA exposes its via its proprietary NVAPI. There is no corresponding support from AMD, so it is simply not possible.

**Comment by Loganbogan9** [comment]
> Yes - vrperfkit only supports DX11 games, and VRS is not available in DX11. NVIDIA exposes its via its proprietary NVAPI. There is no corresponding support from AMD, so it is simply not possible.

Oh duh. Okay got it thanks.
