### ISSUE TITLE
NVIDIA Freestyle/ Image filtering?

### ISSUE THREAD

**Issue by Thrywyn** [fholger/vrperfkit#22]
Hi, would NVIDIA Freestyle/ some sort of image filtering be possible with this? Tweaking black levels/gamma/contrast/saturation would be awesome.

**Comment by fholger** [comment]
This is kind of out of scope for this project; you can use Reshade for these things. Have a look at the build at https://vrtoolkit.retrolux.de/
To use it together with vrperfkit, you can rename either of the dlls to d3d11.dll.
