### ISSUE TITLE
Assetto Corsa: Single eye target

### ISSUE THREAD

**Issue by op2003** [fholger/vrperfkit#23]
Hi,

when starting Assetto Corsa with the dll and conf file placed as instructed the vrperfkit.log is created and the dll seems to load well, but then it repeats the following message forever:

23:35:05 [18032] (DEBUG) VRS: Single eye target, don't know which eye

This is obviously with debug mode enabled. I do not see any radius in game. Any setting I should change?

[vrperfkit.log](https://github.com/fholger/vrperfkit/files/7919419/vrperfkit.log)

**Comment by akhamar** [comment]
Have a look at my same question / issue here : https://github.com/fholger/vrperfkit/issues/19

**Comment by fholger** [comment]
Yes, that means that fixed foveated rendering is not currently working for this game, and you should disable it.

**Comment by op2003** [comment]
Thanks Holger, understood. I‘m using the OpenVR renderer where another user on Reddit reported it’s working with the Oculus renderer for AC.

**Comment by fholger** [comment]
The upscaling portion of the mod should work fine, it's just the fixed foveated / VRS part that is not. It's unlikely that the latter would work for Oculus, either, as that would mean the game renders completely differently for Oculus.

**Comment by op2003** [comment]
Yes, understood as well, thanks. I will test if your FSR implementation works better than the one that comes with CSP. 
I assume the other user used the default config where FSR is enabled and VRS disabled and assumed the performance gains are based on VRS.
