### ISSUE TITLE
Reshade performance weirdness with Vrperfkit active

### ISSUE THREAD

**Issue by vrnord** [fholger/vrperfkit#24]
First, mind-blowingly amazing performance improvement with this mod!  Thank you!

Not game-breaking, but weird issue in SkyrimVR.  Using your old Openvr_api version of FFR or FSR the performance hit from Reshade made sense (I can see in the Reshade statistics tab that the 2 effects I am using take about 0.5-0.6 GPU ms combined; disabling/enabling Reshade effects by hitting Del only slightly affected overall fps).

Now with the DXGI version I activate Reshade by renaming its dll to d3d11.dll, and that works.  However every time I add the Reshade dll with the same two effects my fps drops by 10-20fps consistently (from pretty steady 90fps without Reshade down to the 70's), even though the Reshade statistics tab again shows 0.5-0.6 GPU ms combined.  Disabling Reshade effects via Del key doesn't seem to improve fps noticeably, but removing the Reshade dll from the game folder gets me back to 90fps.  So maybe the 2 dll's are conflicting behind the scenes?

I am monitoring performance in FpsVR but the GPU milliseconds don't seem to match FPS reliably since (I think) much of the work being done by Vrperfkit and Reshade isn't included in the ms it displays, but _is_ included in the FPS.  However I notice that ~9.5ms = ~90fps with only vrperfkit; ~10ms (with both Vrperfkit and Reshade) drops me down to the 70's (tested multiple times loading the same game save and walking the same route).

Maybe you could keep an eye out for any potential conflicts between the two dlls, or maybe an Openvr_api version of Vrperfkit wouldn't experience the same issue?  Thanks!

**Comment by fholger** [comment]
What fpsVR reports should be coming directly from SteamVR, so should be reliable. It is possible that you are getting too close to the frame limit and SteamVR decides to enable motion smoothing proactively. You could try disabling motion smoothing entirely and see if that makes a difference.

**Comment by vrnord** [comment]
Just tested without motion smoothing enabled, and same results.  (I am using WMR (Reverb G2) so I don't think Steam's motion smoothing works for me anyway, and I always have WMR's smoothing turned off because it is so bad.)  

With only vrperfkit I averaged 89.2fps and 9.5 GPU ms (lowest dip maybe 85fps briefly); with the reshade dll added but the effects disabled I averaged 80fps and ~10.7 GPU ms (only rarely spiking above 11ms though; lowest dip 70fps).  However  even with only vrperfkit it would randomly briefly dip below 90fps (into the mid-high 80's) even though neither the GPU nor CPU ms graph showed a spike over 11ms - which I interpret as meaning I am barely hitting 90fps despite frametimes consistently below 10ms: this is behavior I would expect if my frametimes hovered just below 11ms.

So it is weird that I lose >1ms just for having that Reshade dll in the game folder despite having the effects disabled, and it is weird that my fps is lower than my frametimes.

**Comment by vrnord** [comment]
fixed!  I downloaded the most recent reshade dll from your github, rather than the one included with VRVision on Nexus, and now  it behaves normally with Vrperfkit!  Not sure if it is a different version or something, but if anybody else has an issue the fix is to redownload from here.

Sorry to bother you!
