### ISSUE TITLE
Does this work with Unity?

### ISSUE THREAD

**Issue by gramster** [fholger/vrperfkit#27]
This isn't an issue, just a question, but could be helped through documentation. The README points to a location to put the files that seems applicable to Unreal engine games. Its not clear to me from that whether this works with Unity games, and if so, where the files should be placed in that case. Hoping that the README could be clarified a bit.

**Comment by fholger** [comment]
For Unity games, just put it in the main folder where the executable resides. The readme only mentions Unreal specifically because that has a particular folder structure, and the correct placement of the files isn't obvious. For Unity, there's no such complication.

**Comment by gramster** [comment]
Thank you!
