### ISSUE TITLE
Integrate VRToolkit into VrPerKit 

### ISSUE THREAD

**Issue by torgebauer** [fholger/vrperfkit#28]
Maybe it makes sense to add also the VRToolkit https://github.com/retroluxfilm/reshade-vrtoolkit into your performance kit. I have really good results with the reshade vr implementation and still use it. If I combine it with your open fsr implementation the image is oversharpened. Therefore I suggest you integrate the VrToolkit somehow that only one sharpening is applied.

**Comment by fholger** [comment]
Not sure what you want me to do here? You can use both together, just have to rename one of the DLLs to d3d11.dll to avoid the name conflict. And then Reshade is specifically a customizable post-processing toolkit, so you can adjust whatever you want it to do. If you don't want additional sharpening (which absolutely makes sense when combined with FSR), you just need a profile that skips sharpening :)

**Comment by torgebauer** [comment]
> Not sure what you want me to do here? You can use both together, just have to rename one of the DLLs to d3d11.dll to avoid the name conflict. And then Reshade is specifically a customizable post-processing toolkit, so you can adjust whatever you want it to do. If you don't want additional sharpening (which absolutely makes sense when combined with FSR), you just need a profile that skips sharpening :)

Ah okay sorry don't know that I just have to rename the file. Thought you could integrate it somehow in your toolkit because the ReShade VR implementation was also from you.
