### ISSUE TITLE
Doesnt work with Iracing

### ISSUE THREAD

**Issue by frankalexandre72** [fholger/vrperfkit#30]
I've got all working fine with ACC and AMS2, but with Iracing the image loads only on the monitor, in the headset there is no image, only "loading". This is in Oculus mode with a Quest 2. Any idea?

**Comment by frankalexandre72** [comment]
10:09:05 [21044] ======================
10:09:05 [21044] VR Performance Toolkit
10:09:05 [21044] ======================

10:09:05 [21044] Current configuration:
10:09:05 [21044]   Upscaling (CAS) is enabled
10:09:05 [21044]     * Render scale: 1
10:09:05 [21044]     * Sharpness:    1
10:09:05 [21044]     * Radius:       0.6
10:09:05 [21044]     * MIP bias:     enabled
10:09:05 [21044]   Debug mode is disabled
10:09:05 [21044] Currently active hotkeys:
10:09:05 [21044]   * cycleUpscalingMethod 17 113
10:09:05 [21044]   * increaseUpscalingRadius 17 114
10:09:05 [21044]   * decreaseUpscalingRadius 17 115
10:09:05 [21044]   * increaseUpscalingSharpness 17 116
10:09:05 [21044]   * decreaseUpscalingSharpness 17 117
10:09:05 [21044]   * toggleDebugMode 17 112
10:09:05 [21044]   * toggleUpscalingApplyMipBias 17 118
10:09:05 [21044]   * toggleFixedFoveated 18 112
10:09:05 [21044]   * captureOutput 17 119
10:09:05 [21044] Installing hook for LoadLibraryA from 00007FFB6C6204F0 to 00007FFB078BB2C0
10:09:05 [21044] Installing hook for LoadLibraryExA from 00007FFB6C61FBC0 to 00007FFB078BB310
10:09:05 [21044] Installing hook for LoadLibraryW from 00007FFB6C61FEE0 to 00007FFB078BB3F0
10:09:05 [21044] Installing hook for LoadLibraryExW from 00007FFB6C61ADC0 to 00007FFB078BB380
10:09:05 [21044] d3d11.dll is loaded in the process, installing hooks...
10:09:05 [21044] Installing hook for D3D11CreateDevice from 00007FFB660EFCB0 to 00007FFB0789CBA0
10:09:05 [21044] Installing hook for D3D11CreateDeviceAndSwapChain from 00007FFB660EFE20 to 00007FFB0789D020
10:09:08 [21044] Loading DLL at "C:\\Windows\\system32\\dxgi.dll"
10:09:08 [21044] LibOVRRT64_1.dll is loaded in the process, installing hooks...
10:09:08 [21044] Installing hook for ovr_Initialize from 00007FFB02928530 to 00007FFB0789F090
10:09:08 [21044] Installing hook for ovr_GetFovTextureSize from 00007FFB029295F0 to 00007FFB0789EFA0
10:09:08 [21044] Installing hook for ovr_EndFrame from 00007FFB02929980 to 00007FFB0789EE20
10:09:08 [21044] Installing hook for ovr_SubmitFrame from 00007FFB02929A70 to 00007FFB0789F300
10:09:08 [21044] Installing hook for ovr_SubmitFrame2 from 00007FFB02929BC0 to 00007FFB0789F180
10:09:08 [21044] Oculus runtime initialization for version 26
10:09:12 [21044] Initializing Oculus frame submission...
10:09:12 [21044] Game is using D3D11 swapchains, initializing D3D11 resources
10:09:12 [21044] Swap chain has format 5, bind flags 1 and misc flags 9
10:09:12 [21044] Eye 0: submitted textures have resolution 5408x2736
10:09:12 [21044] Eye 0: output resolution is 5408x2736
10:09:12 [21044] Creating output swapchain in format 5
10:09:12 [21044] Game is using a single texture for both eyes
10:09:12 [21044] Trying to load NVAPI...
10:09:12 [21044] Successfully initialized NVAPI; Variable Rate Shading is available.
10:09:12 [21044] Installing virtual function hook for ID3D11DeviceContext::PSSetSamplers
10:09:12 [21044] Installing virtual function hook for ID3D11DeviceContext::OMSetRenderTargets
10:09:12 [21044] Installing virtual function hook for ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews
10:09:12 [21044] D3D11 resource creation complete
10:09:12 [21044] Creating D3D11 resources for CAS upscaling...
10:09:12 [21044] (!) ERROR: Failed during post processing: Failed getting current swapchain index: Null chain pointer provided.
10:09:12 [21044] Removing hook to 00007FFB661C9780
10:09:12 [21044] Removing hook to 00007FFB661C8F50
10:09:12 [21044] Removing hook to 00007FFB661C9D30
10:09:49 [21044] Shutting down

**Comment by philosoma** [comment]
Foveated rendering is working via SteamVR for iRacing.

**Comment by frankalexandre72** [comment]
Unfortunately using Revive make the performance much worse. You'll notice the R bar increase by 1.5 point or more.

**Comment by kiview** [comment]
@frankalexandre72 Are you sure this is not from the wrong settings in SteamVR? AFAIK you should have the resolution in SteamVR at 100% and supersampling turned off.

**Comment by frankalexandre72** [comment]
yeah im sure, its a know problem on the Iracing forum. Happens to everybody.

**Comment by kiview** [comment]
Ok strange, does not happen for me with Revive and Quest 2 with Link on Windows 11. But using Revive fixes the laggy SteamVR tracking and therefore allows me to use vrperfkit.

**Comment by kiview** [comment]
Can confirm, that https://github.com/fholger/vrperfkit/commit/f486b0a391e89b56efa39d412255f6ca13528a51 fixed this for me. Awesome job, thanks!
