### ISSUE TITLE
not working with Star Wars Squadrons

### ISSUE THREAD

**Issue by DrGugl** [fholger/vrperfkit#32]
I can't open it with this Game because EasyAntiCheat blocks it automatically

**Comment by fholger** [comment]
That's expected, and there's nothing I can do about it. Anti-cheat solutions wouldn't be doing their job properly if they weren't blocking custom injection DLLs. You can look around for guides on how to disable EAC for the game; doing so supposedly makes vrperfkit work for the singleplayer, at least.

**Comment by DrGugl** [comment]
Thanks for the reply. There actually is a way to disable the EAC via a custom start.exe. With that the tool also seems to work.
