### ISSUE TITLE
increasing rendertarget

### ISSUE THREAD

**Issue by Fukeung** [fholger/vrperfkit#34]
Hi, can I set a render target higher than 1 and improve quality/sharpness that way?

**Comment by fholger** [comment]
Kind of. If you set renderScale to greater than 1, then the game will render at the default Steam resolution, and the image will then be upscaled to a higher resolution as per your renderScale setting. Obviously, you will not gain any performance doing so. You might also want to try just sharpening the image (set `method: cas` and `renderScale: 1`), as you might find that upscaling offers little additional benefit.
