### ISSUE TITLE
Debug for foveated rendering

### ISSUE THREAD

**Issue by philosoma** [fholger/vrperfkit#37]
Is it possible to draw some rings or something for the foveated rendering rings in debug mode? Would really aid the understanding of where they are and if they can be seen in the headset.

Really impressive mod. Looking forward to the force hidden area mask feature., hopefully additional gains to be had!

**Comment by fholger** [comment]
Not easily. The way FFR works, there's no direct way to highlight where it happens. It would have to be done in a completely separate pass in post-processing, but then there is no actual guarantee that that pass displays the correct rings. In general I'd say that if you can't notice the foveation, but do still get a reduction in GPU time, I wouldn't worry too much about it :)
