### ISSUE TITLE
How to change settings

### ISSUE THREAD

**Issue by BrziJoe** [fholger/vrperfkit#4]
Hi Fholger, you forgot to add "how to" in readme :)

I figured it from log, we suppose to use shortcuts to circle between different settings,  (Alt=17, F1 =112, F2=113...)
**********
13:24:45 [13400] Currently active hotkeys:
13:24:45 [13400]   * cycleUpscalingMethod 17 113 (Alt+F2)
13:24:45 [13400]   * increaseUpscalingRadius 17 114
13:24:45 [13400]   * decreaseUpscalingRadius 17 115
13:24:45 [13400]   * increaseUpscalingSharpness 17 116
13:24:45 [13400]   * decreaseUpscalingSharpness 17 117
13:24:45 [13400]   * toggleDebugMode 17 112
13:24:45 [13400]   * toggleUpscalingApplyMipBias 17 118
13:24:45 [13400]   * captureOutput 17 119
*********

Also there are some settings as default in vrperfkit:
*********
13:24:45 [13400] Current configuration:
13:24:45 [13400]   Upscaling (FSR) is enabled
13:24:45 [13400]     * Render scale: 0.77
13:24:45 [13400]     * Sharpness:    0.7
13:24:45 [13400]     * Radius:       0.6
13:24:45 [13400]     * MIP bias:     enabled
13:24:45 [13400]   Debug mode is disabled
*********

How can I set my preferred settings as my default? Is there some config file to edit?
Or can I save it after using shortcuts?

**Comment by fholger** [comment]
vrperfkit.yml is the config file. Edit it to your heart's content :)
