### ISSUE TITLE
Does not work: iRacing + Oculus 

### ISSUE THREAD

**Issue by bastardo6** [fholger/vrperfkit#41]
Simulator simply will not launch for Oculus user… Quest 2 if that makes a difference.

I was so excited for foveated rendering!! Hope this can be fixed :)

**Comment by mrzoops** [comment]
I just tested with iRacing and the sim loaded and played fine, I am just unable verify that the mod is actually doing anything or running

**Comment by magnazan** [comment]
Quest 2 user here. Sim does load and head is tracked but only the default app loading screen is shown in the headset not the actual game world.

**Comment by tymondouglas** [comment]
Same issue over here, Rift S + Oculus Runtime

**Comment by kiview** [comment]
Can confirm that it does not work with Q2 and Oculus SDK.
From the experiences of other users, it seems it works if used through SteamVR/OpenVR instead.

Any plans to support Oculus directly?

**Comment by fholger** [comment]
Duplicate of #30.
