### ISSUE TITLE
User Overlay

### ISSUE THREAD

**Issue by Enterfrize** [fholger/vrperfkit#43]
Maybe I'm using the utility the wrong way (forgive my ignorance!).  In debug mode, could numeric values be shown onscreen as they are being adjusted?  This way we can write them down and place them directly in the config file when we find exactly what we need.

**Comment by fholger** [comment]
No, not without some effort as that would require some form of UI library. But the values are written to the log file whenever you use the hotkeys to change them, so you can pick them up from there.
