### ISSUE TITLE
Request --  Prediction (Motion) Dampening

### ISSUE THREAD

**Issue by zero2005** [fholger/vrperfkit#44]
OpenXR tool for MSFS recently implemented a feature called " Prediction Dampening" -- which seems like it was mainly used to dampen the movements induced for new Win11 users.

However there are two instances beyond that I can think this might help.
First is for those of us who have buttkickers, and/or just drink too much coffee. Its possible that it can induce weird situations where your view is bouncing around and being tracked by the headset which just feels off, either due to rumbling, or even just a rapid heartbeat.

The second and probably more universal: ZOOM. By zooming in any game, there's no stabilization, unlike flat panel games. This results in really bad images, much like holding high power binoculars.

Ideally, I'd like to be able to rapidly switch between different levels of dampening, so for non-zoom, I could have a low dampening, but when zoomed, higher dampening.

I contacted the developers of the OpenXR tool, and they suggested asking here as they don't know OpenVR, just OpenXR. 
The way they said it is implemented is:
"basically fake out the predicted display time returned by the OpenXR runtime (whether it's the WMR one, Oculus one, SteamVR one)"

This might be asking a lot, I know, but its a feature I'd love to see non the less and I don't know where else to ask.
Or, if you know of any other way to dampen the tracking, especially when in any sort of zoom, I'd be interested.

**Comment by fholger** [comment]
I'm afraid this is out of scope for this mod.
