### ISSUE TITLE
I don't find dxgi.dll

### ISSUE THREAD

**Issue by cocorentin15** [fholger/vrperfkit#45]
Sorry, it's probably stupid, but I don't find the file dxgi.dll  inside the zip/file
Where is it?
Thanks

**Comment by fholger** [comment]
Did you download the vrperfkit_v0.2.2.zip instead of the "Source code (zip)" file? if so, your virus scanner may have eaten the dll.

**Comment by cocorentin15** [comment]
Oh i see, thanks i'm not really good with github 😅
