### ISSUE TITLE
MSFS + Varjo Aero + Foveated render causes strange black outlines on distant terrain.

### ISSUE THREAD

**Issue by jeffdamp-wave** [fholger/vrperfkit#49]
Build: Main branch pulled 2/18/22 built using VS2019 (x64 free)
Title: MSFS2020
Headset: Varjo Aero
Graphics card: Kingpin 3090 
Driver: Nvidia 511.79
DX Version: 11

Enabling VRS (or VRS Custom) will cause strange black lines out at the edge of the horizon or on other distant objects (see attached picture).  The picture was taking with VRS Custom and 1x @ 40% 1/2x @ 80% and 1/16x outer.  The black lines seem to stop right where the inner 40% 1x VRS is.
![image](https://user-images.githubusercontent.com/61430184/154792056-640eed29-6f1c-48d0-9e0b-a680c0d21465.png)

I played around with image quality at 35ppd and 39ppd.  MSFS2020 was actually playable with a 39ppd and VRS enabled!  I could maintain above 30FPS at 100SS and 100 scaling.  and get upper 30s to 40s with a factor of 85%. 
Keep up the good work!  Just need to tighten up the graphics on level 3 ;)

**Comment by fholger** [comment]
Are you sure you posted this to the right project? vrperfkit does not support OpenXR and therefore does not support MSFS. I imagine you are using the OpenXR toolkit: https://github.com/mbucchia/OpenXR-Toolkit

**Comment by jeffdamp-wave** [comment]
> Are you sure you posted this to the right project? vrperfkit does not support OpenXR and therefore does not support MSFS. I imagine you are using the OpenXR toolkit: https://github.com/mbucchia/OpenXR-Toolkit

Oops yes wrong project sorry I'll remove.
