### ISSUE TITLE
Is there a way to throw money at this?

### ISSUE THREAD

**Issue by Riccardo-Jenner** [fholger/vrperfkit#50]
I get it. Open Source Software isn't primarily made to make money, but since this software is mostly used for leisure-stuff anyway and turns out to be really useful I sure wouldn't mind a paypal link/patreon account or whatever to support the effort :).

**Comment by fholger** [comment]
Thanks, I appreciate it. But no, I don't currently accept donations or payments of any kind for my work. I'm financially secure, and opening that door would create more hassle for me than it's worth :) So just enjoy!

**Comment by DJSlane** [comment]
Then thanks! 
There is a future and FSR, FFR/VRS are a certainly part of it in some way. DLSS is a player too. I hope they can play nice. You are bridging that future. With all the frustrations over GPU availability and costs: this was a much needed "shot-in-the-arm"; or, in this case, "injection into the render pipeline". My render-pipeline thanks you. 

Also, it may be a matter of time before VR games inherently incorporate these features and make some of your work redundant or unnecessary, and that makes me incredibly sad somehow, so for the time being I feel like these are heady days in VR. 

On behalf of myself and my kids (who love VR and for whom it will play a larger role of the future). Thank you for bringing this to us!

**Comment by DJSlane** [comment]
Kid in VR. 
![16453987289261762022851551008034](https://user-images.githubusercontent.com/98013339/154868588-58ccff67-b254-4fb3-abdc-999ae12a1fe1.jpg)

**Comment by DJSlane** [comment]
- 
![16453988719279017187770255408190](https://user-images.githubusercontent.com/98013339/154868640-b94034a0-a1d3-493a-8d60-67d887af6b73.jpg)
![16453989084486063980542731730465](https://user-images.githubusercontent.com/98013339/154868644-a1c987ce-b9dc-4b53-8a96-c5bcefd68707.jpg)

**Comment by DJSlane** [comment]
One day we'll laugh at how large and heavy the headset is (hence the two pulleys at the front of the unit)
