### ISSUE TITLE
TAA injection? Is it possible? 

### ISSUE THREAD

**Issue by d0x360** [fholger/vrperfkit#51]
Hi, so Alien Isolation has a VR mod and it also has a separate TAA injection mod.  So is it possible to inject TAA into games that don't have it or did alien isolation have it but it was disabled and they used SMAA instead.. which is weird since TAA looks better and uses less resources...

Both projects are here on GitHub.

**Comment by fholger** [comment]
Not in a generic way, no. TAA (at least what TAA typically entails in modern implementations) is not a pure post-processing effect and requires deeper engine-level integration.

**Comment by d0x360** [comment]
Right, it requires access to the Z buffer I think.  

The reason I bring it up is because surely some if not most game engines have TAA like alien isolation must have.  So then it's a matter of enabling it.

That or the TAA injection mod for alien works in some mysterious ways.

**Comment by fholger** [comment]
It's not just the Z buffer, you also require motion vectors and an understanding of when and how to apply TAA. Like I said, this is engine specific and can't be done in a generic way for any game. Same reason why DLSS can't be generically injected.

**Comment by d0x360** [comment]
Yes I know.  I've read the white paper.  However I'm saying that today...
And probably for the last few years, almost every engine has TAA.

There must be a way to enable it.  I'm not saying you can add it to
something that doesn't have it.  I'm saying its likely there but not user
facing and there is likely a way to enable it however difficult it may be.

How many games are built on Unity or UE?  They both have TAA.  UE has TAAU
now.  It's excellent at anti aliasing and upscaling.  Another setting that
may not be user facing or able to be enabled by via ini edits.. but there's
likely a way to do it although it's surely complicated enough that nobody
would bother.

**Comment by fholger** [comment]
But that would still be engine-specific and possibly even game-specific and not something I can do with this tool.

Just because Unreal has TAA support doesn't mean that it can work in any game built on UE. Render pipelines can be customized, and TAA does have certain requirements that particular choices in the game may conflict with.

**Comment by d0x360** [comment]
I completely agree and I know why it sounds like I don't but I don't think
I could have explained it any different.

Absolutely some developers will have made customizations that would make it
impossible to add something like TAA.

I'm just saying that the code path for TAA is likely in most modern games
and there is probably a way to enable it but... It's out of the scope of
the project and it's understandable why.

You would need to test every game plus the way to enable it is probably
difficult... Very difficult.  Not only that even if say... 10 games made
with the same engine had the ability for someone to modify the game to
enable it... The modification's might be different for 4 of the games.
Just random numbers.

It could be something simple like modifying an ini or it could be much more
complex and basically be mod tier level of work that took a month to get
working only for the developers to update the game a week later which would
probably break the mod but even worse .. they added it to the settings menu
because for them it's just a couple of clicks in the menu and then some
number values like sample counts, sharpening etc...


I think I've written enough lol.  I was basically just curious if such a
thing was determined to be easy like in alien isolation and some other
games, if there was a chance to add the option for them.  That's all.

I wouldn't expect you to go crazy trying to get it everywhere.  Trust me
you are already doing plenty.
