### ISSUE TITLE
Hotkeys can be triggered with separated key presses

### ISSUE THREAD

**Issue by jelkand** [fholger/vrperfkit#55]
When running VR Perf Kit with hotkeys enabled, I can press F1, wait some time, then press ctrl, and toggle debug mode.

Interestingly, the reverse does not seem to be true, but I did not test it extensively.

This was using a Valve Index, playing DCS, running the most recent release. I was using a default vrperfkit.yml. Let me know if there is a log file i should provide.

**Comment by DJSlane** [comment]
Yeah I've noted that too. In my case I had even tried changing it to be the combo of alt and ctrl plus all the function keys to make it so it didn't interfere with a particular game, but that also occurs for me. Not sure if it happens with all commands, but it's not key-specific as I also had remapped the debug to a different hotkey and it does that. I had mapped LCtrl+LAlt+Z for FPSVR and as I do so it brings up the debug.
