### ISSUE TITLE
Toggle between scaling methods and disabled

### ISSUE THREAD

**Issue by tommaier123** [fholger/vrperfkit#56]
It would be very useful for performance testing if you could disable the upscaling with a hotkey. For example with the same hotkey as toggling between the scaling methods.

**Comment by fholger** [comment]
Not possible, unfortunately. Disabling scaling would rely on the game actually reacting to resolution changes on the fly, and not all games do that. So disabling the scaling would either return you to native resolution or keep the game at a lower resolution without upscaling. And the result would depend entirely on the game.

The only reliable thing I could do is to always keep the games at the lower resolution, but just disable the upscaling pass. That way you could see the visual improvement from the upscaling and its performance cost. But you will never be able to reliably compare directly to native rendering.

**Comment by tommaier123** [comment]
Makes sense. I guess adjusting the resolution would only work reliably on SteamVR, since it's actually a feature there.
