### ISSUE TITLE
Dynamic scaling factor based on fps/ auto resulution compatibility

### ISSUE THREAD

**Issue by tommaier123** [fholger/vrperfkit#57]
For many VR Rhythm games where fps is more important than resolution this tool can't be used because it is not compatible with SteamVR auto resolution. So it would be very useful if the tool would either work with the SteamVR auto resolution or adjust the scaling factor/render resolution dynamically so the fps stays consistent.

**Comment by fholger** [comment]
I may have missed something here, but far as I know, SteamVR does *not* dynamically adjust resolution. Auto resolution, to my knowledge, merely chooses a resolution scaling based on your expected GPU performance, but it's still a fixed resolution. VRPerfkit absolutely does work with that - it's always relative to whatever SteamVR reports as the desired render resolution.

As for dynamic resolution scaling, same issue as my answer in your other ticket.

**Comment by tommaier123** [comment]
Ah yes, I think you are right. It probably chooses a low resolution for my graphics card so even the upscaling can't make it sharp. Rather than auto resolution I should set the SteamVR resolution to 100% and adjust the upscaling per game so it runs smooth.
