### ISSUE TITLE
Can this work with XPLANE (Vulkan) 

### ISSUE THREAD

**Issue by wakevortex** [fholger/vrperfkit#59]
As the title says , I assumed as Xplane uses OPEN VR,(via SteamVR)  this would work, but I get an error in the log 

18:13:17 [7260] (!) ERROR: Failed to initialize OpenVR resources. Game may be using an unsupported graphics API
18:13:17 [7260] OpenVR: requested interface IVRSettings_003
18:13:17 [7260] (DEBUG) Redirecting CreateDXGIFactory1 to system
18:13:17 [7260] Loading DLL at "C:\\WINDOWS\\system32\\dxgi.dll"

Im a little confused..is this a lost cause on Xplane in VR?
Thanks 
Bill P

**Comment by wakevortex** [comment]
aaah I didnt realise that about D3D11 only...
Xplane CAN run in OpenGL  rather than Vulkan ..I assume that is also a non starter then?

**Comment by fholger** [comment]
Yeah, OpenGL isn't supported, either.

**Comment by BeigeAnimal** [comment]
> Only D3D11 is supported by vrperfkit. If the game is rendering with Vulkan, then it is not going to work.

Can you please add that to the readme then, I know the other one that replaces the openvr dll has it in it's readme, I thought this might be Vulkan compatible since nothing was mentioned here.

**Comment by d0x360** [comment]
> 

Most likely yes.
