### ISSUE TITLE
cant find dxgi.dll 

### ISSUE THREAD

**Issue by timwalsh42ndsqd** [fholger/vrperfkit#60]
sorry , im being dumb ... where is the dxgi.dll file in the zip folder ? sorry if this as a silly question , thanks.

**Comment by philosoma** [comment]
https://github.com/fholger/vrperfkit/releases

**Comment by timwalsh42ndsqd** [comment]
Thanks so much 👌🤩

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by timwalsh42ndsqd** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
