### ISSUE TITLE
Question: When migrating from OpenVRFSR

### ISSUE THREAD

**Issue by ni1chigo2115** [fholger/vrperfkit#9]
Apparently there are some bugs as far as the issue is concerned, but I would like to make my intentions in good time.
Simple question. If I have an app that originally had OpenVRFSR installed, should I run a repair on Steam to restore the openvrapi.dll to the original openvrapi.dll instead of renaming and replacing the dxgi.dll from FSR?
(Some people might want to integrate with Reshade, but let's leave that for now)

Translated with www.DeepL.com/Translator (free version)

**Comment by fholger** [comment]
Yes, you need to restore the original openvr_api.dll. vrperfkit must be installed as dxgi.dll or d3d11.dll, it will not work if you rename it to openvr_api.dll.

**Comment by ni1chigo2115** [comment]
Thank you! So, instead of putting it in the plugin(x86) folder, I need to put it in the same hierarchy as the app.
I was surprised to see the x86 folder and the dxgi plugin in it.

**Comment by Zorinco96** [comment]
> Apparently there are some bugs as far as the issue is concerned, but I would like to make my intentions in good time. Simple question. If I have an app that originally had OpenVRFSR installed, should I run a repair on Steam to restore the openvrapi.dll to the original openvrapi.dll instead of renaming and replacing the dxgi.dll from FSR? (Some people might want to integrate with Reshade, but let's leave that for now)
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

Is there a way to integrate ReShade? I've been using the VrFSR mod for a while with DCS, along with ReShade and it'd be nice to keep that option.

**Comment by fholger** [comment]
I haven't tested if they work together, but you can rename either of the DLLs to d3d11.dll to install them alongside each other.

**Comment by Zorinco96** [comment]
Perfect, worked like a charm!

**Comment by glenmurphy** [comment]
> I haven't tested if they work together, but you can rename either of the DLLs to d3d11.dll to install them alongside each other.

Does the naming impact the order in how reshade and vrperfkit are applied? e.g. you probably want reshade applied before upscaling

**Comment by fholger** [comment]
In theory, dxgi should be loaded first, so that's what you'd want Reshade to be to get it to inject first. Can't really make any guarantees, though.
